---@meta
---@class ImprovedFog
---@field getAlphaCircleAlpha any
---@field getAlphaCircleRad any
---@field getBaseAlpha any
---@field getBottomAlphaHeight any
---@field getColorB any
---@field getColorG any
---@field getColorR any
---@field getMaxXOffset any
---@field getMaxYOffset any
---@field getMinXOffset any
---@field getOctaves any
---@field getRenderEveryXRow any
---@field getRenderXRowsFromCenter any
---@field getSecondLayerAlpha any
---@field getTopAlphaHeight any
---@field isDrawDebugColors any
---@field isEnableEditing any
---@field isHighQuality any
---@field isRenderCurrentLayerOnly any
---@field isRenderEndOnly any
---@field isRenderOnlyOneRow any
---@field setAlphaCircleAlpha any
---@field setAlphaCircleRad any
---@field setBaseAlpha any
---@field setBottomAlphaHeight any
---@field setColorB any
---@field setColorG any
---@field setColorR any
---@field setDrawDebugColors any
---@field setEnableEditing any
---@field setHighQuality any
---@field setMaxXOffset any
---@field setMaxYOffset any
---@field setMinXOffset any
---@field setOctaves any
---@field setRenderCurrentLayerOnly any
---@field setRenderEndOnly any
---@field setRenderEveryXRow any
---@field setRenderOnlyOneRow any
---@field setRenderXRowsFromCenter any
---@field setSecondLayerAlpha any
---@field setTopAlphaHeight any
ImprovedFog = ImprovedFog or {}

function ImprovedFog.getAlphaCircleAlpha() end
function ImprovedFog.getAlphaCircleRad() end
function ImprovedFog.getBaseAlpha() end
function ImprovedFog.getBottomAlphaHeight() end
function ImprovedFog.getColorB() end
function ImprovedFog.getColorG() end
function ImprovedFog.getColorR() end
function ImprovedFog.getMaxXOffset() end
function ImprovedFog.getMaxYOffset() end
function ImprovedFog.getMinXOffset() end
function ImprovedFog.getOctaves() end
function ImprovedFog.getRenderEveryXRow() end
function ImprovedFog.getRenderXRowsFromCenter() end
function ImprovedFog.getSecondLayerAlpha() end
function ImprovedFog.getTopAlphaHeight() end
function ImprovedFog.isDrawDebugColors() end
function ImprovedFog.isEnableEditing() end
function ImprovedFog.isHighQuality() end
function ImprovedFog.isRenderCurrentLayerOnly() end
function ImprovedFog.isRenderEndOnly() end
function ImprovedFog.isRenderOnlyOneRow() end
function ImprovedFog.setAlphaCircleAlpha() end
function ImprovedFog.setAlphaCircleRad() end
function ImprovedFog.setBaseAlpha() end
function ImprovedFog.setBottomAlphaHeight() end
function ImprovedFog.setColorB() end
function ImprovedFog.setColorG() end
function ImprovedFog.setColorR() end
function ImprovedFog.setDrawDebugColors() end
function ImprovedFog.setEnableEditing() end
function ImprovedFog.setHighQuality() end
function ImprovedFog.setMaxXOffset() end
function ImprovedFog.setMaxYOffset() end
function ImprovedFog.setMinXOffset() end
function ImprovedFog.setOctaves() end
function ImprovedFog.setRenderCurrentLayerOnly() end
function ImprovedFog.setRenderEndOnly() end
function ImprovedFog.setRenderEveryXRow() end
function ImprovedFog.setRenderOnlyOneRow() end
function ImprovedFog.setRenderXRowsFromCenter() end
function ImprovedFog.setSecondLayerAlpha() end
function ImprovedFog.setTopAlphaHeight() end
