---@meta
---@class LootMaps
---@field DEFAULT_MAP_DIRECTORY any
---@field Init any
---@field callLua any
---@field DEFAULT_MAP_DIRECTORY any
---@field Init any
LootMaps = LootMaps or {}

function LootMaps.callLua() end
function LootMaps.callLua(functionName, mapUI, arg1, arg2, arg3, arg4) end
---@class LootMaps_Init
---@field BBurgStashMap1 any
---@field BBurgStashMap2 any
---@field BBurgStashMap3 any
---@field BBurgStashMap4 any
---@field BBurgStashMap5 any
---@field BBurgStashMap6 any
---@field BBurgStashMap7 any
---@field BBurgStashMap8 any
---@field EkronStashMap1 any
---@field EkronStashMap2 any
---@field EkronStashMap3 any
---@field EkronStashMap4 any
---@field EkronStashMap5 any
---@field EkronStashMap6 any
---@field EkronStashMap7 any
---@field EkronStashMap8 any
---@field IrvingtonStashMap1 any
---@field IrvingtonStashMap10 any
---@field IrvingtonStashMap2 any
---@field IrvingtonStashMap3 any
---@field IrvingtonStashMap4 any
---@field IrvingtonStashMap5 any
---@field IrvingtonStashMap6 any
---@field IrvingtonStashMap7 any
---@field IrvingtonStashMap8 any
---@field IrvingtonStashMap9 any
---@field LouisvilleMap1 any
---@field LouisvilleMap2 any
---@field LouisvilleMap3 any
---@field LouisvilleMap4 any
---@field LouisvilleMap5 any
---@field LouisvilleMap6 any
---@field LouisvilleMap7 any
---@field LouisvilleMap8 any
---@field LouisvilleMap9 any
---@field LouisvilleStashMap1 any
---@field LouisvilleStashMap10 any
---@field LouisvilleStashMap11 any
---@field LouisvilleStashMap12 any
---@field LouisvilleStashMap13 any
---@field LouisvilleStashMap14 any
---@field LouisvilleStashMap15 any
---@field LouisvilleStashMap16 any
---@field LouisvilleStashMap2 any
---@field LouisvilleStashMap3 any
---@field LouisvilleStashMap4 any
---@field LouisvilleStashMap5 any
---@field LouisvilleStashMap6 any
---@field LouisvilleStashMap7 any
---@field LouisvilleStashMap8 any
---@field LouisvilleStashMap9 any
---@field MarchRidgeMap any
---@field MarchRidgeStashMap1 any
---@field MarchRidgeStashMap10 any
---@field MarchRidgeStashMap2 any
---@field MarchRidgeStashMap3 any
---@field MarchRidgeStashMap4 any
---@field MarchRidgeStashMap5 any
---@field MarchRidgeStashMap6 any
---@field MarchRidgeStashMap7 any
---@field MarchRidgeStashMap8 any
---@field MarchRidgeStashMap9 any
---@field MulStashMap1 any
---@field MulStashMap10 any
---@field MulStashMap11 any
---@field MulStashMap12 any
---@field MulStashMap13 any
---@field MulStashMap14 any
---@field MulStashMap15 any
---@field MulStashMap16 any
---@field MulStashMap17 any
---@field MulStashMap18 any
---@field MulStashMap19 any
---@field MulStashMap2 any
---@field MulStashMap3 any
---@field MulStashMap4 any
---@field MulStashMap5 any
---@field MulStashMap6 any
---@field MulStashMap7 any
---@field MulStashMap8 any
---@field MulStashMap9 any
---@field MuldraughMap any
---@field RiversideMap any
---@field RiversideStashMap1 any
---@field RiversideStashMap10 any
---@field RiversideStashMap2 any
---@field RiversideStashMap3 any
---@field RiversideStashMap4 any
---@field RiversideStashMap5 any
---@field RiversideStashMap6 any
---@field RiversideStashMap7 any
---@field RiversideStashMap8 any
---@field RiversideStashMap9 any
---@field RosewoodMap any
---@field RosewoodStashMap1 any
---@field RosewoodStashMap2 any
---@field RosewoodStashMap3 any
---@field RosewoodStashMap4 any
---@field RosewoodStashMap5 any
---@field WestpointMap any
---@field WorldStashMap1 any
---@field WorldStashMap10 any
---@field WorldStashMap11 any
---@field WorldStashMap12 any
---@field WorldStashMap13 any
---@field WorldStashMap14 any
---@field WorldStashMap15 any
---@field WorldStashMap16 any
---@field WorldStashMap17 any
---@field WorldStashMap18 any
---@field WorldStashMap19 any
---@field WorldStashMap2 any
---@field WorldStashMap20 any
---@field WorldStashMap21 any
---@field WorldStashMap22 any
---@field WorldStashMap23 any
---@field WorldStashMap3 any
---@field WorldStashMap4 any
---@field WorldStashMap5 any
---@field WorldStashMap6 any
---@field WorldStashMap7 any
---@field WorldStashMap8 any
---@field WorldStashMap9 any
---@field WpStashMap1 any
---@field WpStashMap10 any
---@field WpStashMap11 any
---@field WpStashMap12 any
---@field WpStashMap13 any
---@field WpStashMap14 any
---@field WpStashMap15 any
---@field WpStashMap16 any
---@field WpStashMap2 any
---@field WpStashMap3 any
---@field WpStashMap4 any
---@field WpStashMap5 any
---@field WpStashMap6 any
---@field WpStashMap7 any
---@field WpStashMap8 any
---@field WpStashMap9 any
---@field BBurgStashMap1 any
---@field BBurgStashMap2 any
---@field BBurgStashMap3 any
---@field BBurgStashMap4 any
---@field BBurgStashMap5 any
---@field BBurgStashMap6 any
---@field BBurgStashMap7 any
---@field BBurgStashMap8 any
---@field EkronStashMap1 any
---@field EkronStashMap2 any
---@field EkronStashMap3 any
---@field EkronStashMap4 any
---@field EkronStashMap5 any
---@field EkronStashMap6 any
---@field EkronStashMap7 any
---@field EkronStashMap8 any
---@field IrvingtonStashMap1 any
---@field IrvingtonStashMap10 any
---@field IrvingtonStashMap2 any
---@field IrvingtonStashMap3 any
---@field IrvingtonStashMap4 any
---@field IrvingtonStashMap5 any
---@field IrvingtonStashMap6 any
---@field IrvingtonStashMap7 any
---@field IrvingtonStashMap8 any
---@field IrvingtonStashMap9 any
---@field LouisvilleMap1 any
---@field LouisvilleMap2 any
---@field LouisvilleMap3 any
---@field LouisvilleMap4 any
---@field LouisvilleMap5 any
---@field LouisvilleMap6 any
---@field LouisvilleMap7 any
---@field LouisvilleMap8 any
---@field LouisvilleMap9 any
---@field LouisvilleStashMap1 any
---@field LouisvilleStashMap10 any
---@field LouisvilleStashMap11 any
---@field LouisvilleStashMap12 any
---@field LouisvilleStashMap13 any
---@field LouisvilleStashMap14 any
---@field LouisvilleStashMap15 any
---@field LouisvilleStashMap16 any
---@field LouisvilleStashMap2 any
---@field LouisvilleStashMap3 any
---@field LouisvilleStashMap4 any
---@field LouisvilleStashMap5 any
---@field LouisvilleStashMap6 any
---@field LouisvilleStashMap7 any
---@field LouisvilleStashMap8 any
---@field LouisvilleStashMap9 any
---@field MarchRidgeMap any
---@field MarchRidgeStashMap1 any
---@field MarchRidgeStashMap10 any
---@field MarchRidgeStashMap2 any
---@field MarchRidgeStashMap3 any
---@field MarchRidgeStashMap4 any
---@field MarchRidgeStashMap5 any
---@field MarchRidgeStashMap6 any
---@field MarchRidgeStashMap7 any
---@field MarchRidgeStashMap8 any
---@field MarchRidgeStashMap9 any
---@field MulStashMap1 any
---@field MulStashMap10 any
---@field MulStashMap11 any
---@field MulStashMap12 any
---@field MulStashMap13 any
---@field MulStashMap14 any
---@field MulStashMap15 any
---@field MulStashMap16 any
---@field MulStashMap17 any
---@field MulStashMap18 any
---@field MulStashMap19 any
---@field MulStashMap2 any
---@field MulStashMap3 any
---@field MulStashMap4 any
---@field MulStashMap5 any
---@field MulStashMap6 any
---@field MulStashMap7 any
---@field MulStashMap8 any
---@field MulStashMap9 any
---@field MuldraughMap any
---@field RiversideMap any
---@field RiversideStashMap1 any
---@field RiversideStashMap10 any
---@field RiversideStashMap2 any
---@field RiversideStashMap3 any
---@field RiversideStashMap4 any
---@field RiversideStashMap5 any
---@field RiversideStashMap6 any
---@field RiversideStashMap7 any
---@field RiversideStashMap8 any
---@field RiversideStashMap9 any
---@field RosewoodMap any
---@field RosewoodStashMap1 any
---@field RosewoodStashMap2 any
---@field RosewoodStashMap3 any
---@field RosewoodStashMap4 any
---@field RosewoodStashMap5 any
---@field WestpointMap any
---@field WorldStashMap1 any
---@field WorldStashMap10 any
---@field WorldStashMap11 any
---@field WorldStashMap12 any
---@field WorldStashMap13 any
---@field WorldStashMap14 any
---@field WorldStashMap15 any
---@field WorldStashMap16 any
---@field WorldStashMap17 any
---@field WorldStashMap18 any
---@field WorldStashMap19 any
---@field WorldStashMap2 any
---@field WorldStashMap20 any
---@field WorldStashMap21 any
---@field WorldStashMap22 any
---@field WorldStashMap23 any
---@field WorldStashMap3 any
---@field WorldStashMap4 any
---@field WorldStashMap5 any
---@field WorldStashMap6 any
---@field WorldStashMap7 any
---@field WorldStashMap8 any
---@field WorldStashMap9 any
---@field WpStashMap1 any
---@field WpStashMap10 any
---@field WpStashMap11 any
---@field WpStashMap12 any
---@field WpStashMap13 any
---@field WpStashMap14 any
---@field WpStashMap15 any
---@field WpStashMap16 any
---@field WpStashMap2 any
---@field WpStashMap3 any
---@field WpStashMap4 any
---@field WpStashMap5 any
---@field WpStashMap6 any
---@field WpStashMap7 any
---@field WpStashMap8 any
---@field WpStashMap9 any
LootMaps.Init = LootMaps.Init or {}
function LootMaps.Init.BBurgStashMap1(mapUI) end
function LootMaps.Init.BBurgStashMap2(mapUI) end
function LootMaps.Init.BBurgStashMap3(mapUI) end
function LootMaps.Init.BBurgStashMap4(mapUI) end
function LootMaps.Init.BBurgStashMap5(mapUI) end
function LootMaps.Init.BBurgStashMap6(mapUI) end
function LootMaps.Init.BBurgStashMap7(mapUI) end
function LootMaps.Init.BBurgStashMap8(mapUI) end
function LootMaps.Init.EkronStashMap1(mapUI) end
function LootMaps.Init.EkronStashMap2(mapUI) end
function LootMaps.Init.EkronStashMap3(mapUI) end
function LootMaps.Init.EkronStashMap4(mapUI) end
function LootMaps.Init.EkronStashMap5(mapUI) end
function LootMaps.Init.EkronStashMap6(mapUI) end
function LootMaps.Init.EkronStashMap7(mapUI) end
function LootMaps.Init.EkronStashMap8(mapUI) end
function LootMaps.Init.IrvingtonStashMap1(mapUI) end
function LootMaps.Init.IrvingtonStashMap10(mapUI) end
function LootMaps.Init.IrvingtonStashMap2(mapUI) end
function LootMaps.Init.IrvingtonStashMap3(mapUI) end
function LootMaps.Init.IrvingtonStashMap4(mapUI) end
function LootMaps.Init.IrvingtonStashMap5(mapUI) end
function LootMaps.Init.IrvingtonStashMap6(mapUI) end
function LootMaps.Init.IrvingtonStashMap7(mapUI) end
function LootMaps.Init.IrvingtonStashMap8(mapUI) end
function LootMaps.Init.IrvingtonStashMap9(mapUI) end
function LootMaps.Init.LouisvilleMap1(mapUI) end
function LootMaps.Init.LouisvilleMap2(mapUI) end
function LootMaps.Init.LouisvilleMap3(mapUI) end
function LootMaps.Init.LouisvilleMap4(mapUI) end
function LootMaps.Init.LouisvilleMap5(mapUI) end
function LootMaps.Init.LouisvilleMap6(mapUI) end
function LootMaps.Init.LouisvilleMap7(mapUI) end
function LootMaps.Init.LouisvilleMap8(mapUI) end
function LootMaps.Init.LouisvilleMap9(mapUI) end
function LootMaps.Init.LouisvilleStashMap1(mapUI) end
function LootMaps.Init.LouisvilleStashMap10(mapUI) end
function LootMaps.Init.LouisvilleStashMap11(mapUI) end
function LootMaps.Init.LouisvilleStashMap12(mapUI) end
function LootMaps.Init.LouisvilleStashMap13(mapUI) end
function LootMaps.Init.LouisvilleStashMap14(mapUI) end
function LootMaps.Init.LouisvilleStashMap15(mapUI) end
function LootMaps.Init.LouisvilleStashMap16(mapUI) end
function LootMaps.Init.LouisvilleStashMap2(mapUI) end
function LootMaps.Init.LouisvilleStashMap3(mapUI) end
function LootMaps.Init.LouisvilleStashMap4(mapUI) end
function LootMaps.Init.LouisvilleStashMap5(mapUI) end
function LootMaps.Init.LouisvilleStashMap6(mapUI) end
function LootMaps.Init.LouisvilleStashMap7(mapUI) end
function LootMaps.Init.LouisvilleStashMap8(mapUI) end
function LootMaps.Init.LouisvilleStashMap9(mapUI) end
function LootMaps.Init.MarchRidgeMap(mapUI) end
function LootMaps.Init.MarchRidgeStashMap1(mapUI) end
function LootMaps.Init.MarchRidgeStashMap10(mapUI) end
function LootMaps.Init.MarchRidgeStashMap2(mapUI) end
function LootMaps.Init.MarchRidgeStashMap3(mapUI) end
function LootMaps.Init.MarchRidgeStashMap4(mapUI) end
function LootMaps.Init.MarchRidgeStashMap5(mapUI) end
function LootMaps.Init.MarchRidgeStashMap6(mapUI) end
function LootMaps.Init.MarchRidgeStashMap7(mapUI) end
function LootMaps.Init.MarchRidgeStashMap8(mapUI) end
function LootMaps.Init.MarchRidgeStashMap9(mapUI) end
function LootMaps.Init.MulStashMap1(mapUI) end
function LootMaps.Init.MulStashMap10(mapUI) end
function LootMaps.Init.MulStashMap11(mapUI) end
function LootMaps.Init.MulStashMap12(mapUI) end
function LootMaps.Init.MulStashMap13(mapUI) end
function LootMaps.Init.MulStashMap14(mapUI) end
function LootMaps.Init.MulStashMap15(mapUI) end
function LootMaps.Init.MulStashMap16(mapUI) end
function LootMaps.Init.MulStashMap17(mapUI) end
function LootMaps.Init.MulStashMap18(mapUI) end
function LootMaps.Init.MulStashMap19(mapUI) end
function LootMaps.Init.MulStashMap2(mapUI) end
function LootMaps.Init.MulStashMap3(mapUI) end
function LootMaps.Init.MulStashMap4(mapUI) end
function LootMaps.Init.MulStashMap5(mapUI) end
function LootMaps.Init.MulStashMap6(mapUI) end
function LootMaps.Init.MulStashMap7(mapUI) end
function LootMaps.Init.MulStashMap8(mapUI) end
function LootMaps.Init.MulStashMap9(mapUI) end
function LootMaps.Init.MuldraughMap(mapUI) end
function LootMaps.Init.RiversideMap(mapUI) end
function LootMaps.Init.RiversideStashMap1(mapUI) end
function LootMaps.Init.RiversideStashMap10(mapUI) end
function LootMaps.Init.RiversideStashMap2(mapUI) end
function LootMaps.Init.RiversideStashMap3(mapUI) end
function LootMaps.Init.RiversideStashMap4(mapUI) end
function LootMaps.Init.RiversideStashMap5(mapUI) end
function LootMaps.Init.RiversideStashMap6(mapUI) end
function LootMaps.Init.RiversideStashMap7(mapUI) end
function LootMaps.Init.RiversideStashMap8(mapUI) end
function LootMaps.Init.RiversideStashMap9(mapUI) end
function LootMaps.Init.RosewoodMap(mapUI) end
function LootMaps.Init.RosewoodStashMap1(mapUI) end
function LootMaps.Init.RosewoodStashMap2(mapUI) end
function LootMaps.Init.RosewoodStashMap3(mapUI) end
function LootMaps.Init.RosewoodStashMap4(mapUI) end
function LootMaps.Init.RosewoodStashMap5(mapUI) end
function LootMaps.Init.WestpointMap(mapUI) end
function LootMaps.Init.WorldStashMap1(mapUI) end
function LootMaps.Init.WorldStashMap10(mapUI) end
function LootMaps.Init.WorldStashMap11(mapUI) end
function LootMaps.Init.WorldStashMap12(mapUI) end
function LootMaps.Init.WorldStashMap13(mapUI) end
function LootMaps.Init.WorldStashMap14(mapUI) end
function LootMaps.Init.WorldStashMap15(mapUI) end
function LootMaps.Init.WorldStashMap16(mapUI) end
function LootMaps.Init.WorldStashMap17(mapUI) end
function LootMaps.Init.WorldStashMap18(mapUI) end
function LootMaps.Init.WorldStashMap19(mapUI) end
function LootMaps.Init.WorldStashMap2(mapUI) end
function LootMaps.Init.WorldStashMap20(mapUI) end
function LootMaps.Init.WorldStashMap21(mapUI) end
function LootMaps.Init.WorldStashMap22(mapUI) end
function LootMaps.Init.WorldStashMap23(mapUI) end
function LootMaps.Init.WorldStashMap3(mapUI) end
function LootMaps.Init.WorldStashMap4(mapUI) end
function LootMaps.Init.WorldStashMap5(mapUI) end
function LootMaps.Init.WorldStashMap6(mapUI) end
function LootMaps.Init.WorldStashMap7(mapUI) end
function LootMaps.Init.WorldStashMap8(mapUI) end
function LootMaps.Init.WorldStashMap9(mapUI) end
function LootMaps.Init.WpStashMap1(mapUI) end
function LootMaps.Init.WpStashMap10(mapUI) end
function LootMaps.Init.WpStashMap11(mapUI) end
function LootMaps.Init.WpStashMap12(mapUI) end
function LootMaps.Init.WpStashMap13(mapUI) end
function LootMaps.Init.WpStashMap14(mapUI) end
function LootMaps.Init.WpStashMap15(mapUI) end
function LootMaps.Init.WpStashMap16(mapUI) end
function LootMaps.Init.WpStashMap2(mapUI) end
function LootMaps.Init.WpStashMap3(mapUI) end
function LootMaps.Init.WpStashMap4(mapUI) end
function LootMaps.Init.WpStashMap5(mapUI) end
function LootMaps.Init.WpStashMap6(mapUI) end
function LootMaps.Init.WpStashMap7(mapUI) end
function LootMaps.Init.WpStashMap8(mapUI) end
function LootMaps.Init.WpStashMap9(mapUI) end
