---@meta
---@class OpeningHours
---@field Add any
---@field AddPlayer any
---@field CheckHordeSpawn any
---@field CheckMetalGates any
---@field EveryDays any
---@field EveryTenMinutes any
---@field OnGameStart any
---@field OnInitWorld any
---@field OnPlayerUpdate any
---@field RemovePlayer any
---@field Render any
---@field ResetMetalGates any
---@field dayCount any
---@field dayToRespawn any
---@field doors any
---@field gameMode any
---@field hourOfDay any
---@field id any
---@field image any
---@field metalGates any
---@field northSpawn1 any
---@field northSpawn1X any
---@field northSpawn1Y any
---@field northSpawn1Z any
---@field northSpawn2 any
---@field northSpawn2X any
---@field northSpawn2Y any
---@field northSpawn2Z any
---@field northUpstairsSpawn1 any
---@field northUpstairsSpawn1X any
---@field northUpstairsSpawn1Y any
---@field northUpstairsSpawn1Z any
---@field openTime any
---@field png any
---@field southSpawn any
---@field southSpawnX any
---@field southSpawnY any
---@field southSpawnZ any
---@field westSpawn any
---@field westSpawnX any
---@field westSpawnY any
---@field westSpawnZ any
---@field world any
---@field x any
---@field y any
---@field z any
---@field Add any
---@field AddPlayer any
---@field CheckHordeSpawn any
---@field CheckMetalGates any
---@field EveryDays any
---@field EveryTenMinutes any
---@field OnGameStart any
---@field OnInitWorld any
---@field OnPlayerUpdate any
---@field RemovePlayer any
---@field Render any
---@field ResetMetalGates any
---@field dayCount any
---@field dayToRespawn any
---@field doors any
---@field gameMode any
---@field hourOfDay any
---@field id any
---@field image any
---@field metalGates any
---@field northSpawn1 any
---@field northSpawn1X any
---@field northSpawn1Y any
---@field northSpawn1Z any
---@field northSpawn2 any
---@field northSpawn2X any
---@field northSpawn2Y any
---@field northSpawn2Z any
---@field northUpstairsSpawn1 any
---@field northUpstairsSpawn1X any
---@field northUpstairsSpawn1Y any
---@field northUpstairsSpawn1Z any
---@field openTime any
---@field southSpawn any
---@field southSpawnX any
---@field southSpawnY any
---@field southSpawnZ any
---@field westSpawn any
---@field westSpawnX any
---@field westSpawnY any
---@field westSpawnZ any
---@field world any
---@field x any
---@field y any
---@field z any
OpeningHours = OpeningHours or {}

function OpeningHours.Add() end
function OpeningHours.AddPlayer(playerNum, playerObj) end
function OpeningHours.CheckHordeSpawn() end
function OpeningHours.CheckHordeSpawn(regionName, regionSpawn, regionSpawnX, regionSpawnY, regionSpawnZ) end
function OpeningHours.CheckMetalGates() end
function OpeningHours.CheckMetalGates(area) end
function OpeningHours.EveryDays() end
function OpeningHours.EveryTenMinutes() end
function OpeningHours.OnGameStart() end
function OpeningHours.OnInitWorld() end
function OpeningHours.OnPlayerUpdate() end
function OpeningHours.RemovePlayer(p) end
function OpeningHours.Render() end
function OpeningHours.ResetMetalGates() end
function OpeningHours.ResetMetalGates(area) end
