---@meta
---@class rabbit
---@field aliveAnimals any
---@field aliveBreed any
---@field baits any
---@field canBeAlive any
---@field item any
---@field maxHour any
---@field maxSize any
---@field minHour any
---@field minSize any
---@field strength any
---@field traps any
---@field type any
---@field zone any
---@field aliveAnimals any
---@field aliveBreed any
---@field baits any
---@field canBeAlive any
---@field item any
---@field maxHour any
---@field maxSize any
---@field minHour any
---@field minSize any
---@field strength any
---@field traps any
---@field type any
---@field zone any
rabbit = rabbit or {}

