---@meta
---@class Recipe
---@field GetItemTypes any
---@field JewelTable any
---@field LowerBodyClothing any
---@field MysteryCans any
---@field OnCanPerform any
---@field OnCreate any
---@field OnGiveXP any
---@field OnTest any
---@field ScratchTicketWinnings any
---@field WeaponParts any
---@field GetItemTypes any
---@field JewelTable any
---@field LowerBodyClothing any
---@field MysteryCans any
---@field OnCanPerform any
---@field OnCreate any
---@field OnGiveXP any
---@field OnTest any
---@field ScratchTicketWinnings any
---@field WeaponParts any
Recipe = Recipe or {}

---@class Recipe_GetItemTypes
---@field AnimalBrain any
---@field AnimalHead any
---@field CraftLogStack any
---@field CraftSheetRope any
---@field DismantleDigitalWatch any
---@field FishingLine any
---@field MeatCleaver any
---@field MixingUtensil any
Recipe.GetItemTypes = Recipe.GetItemTypes or {}
function Recipe.GetItemTypes.AnimalBrain() end
function Recipe.GetItemTypes.AnimalHead() end
function Recipe.GetItemTypes.CraftLogStack() end
function Recipe.GetItemTypes.CraftSheetRope() end
function Recipe.GetItemTypes.DismantleDigitalWatch() end
function Recipe.GetItemTypes.FishingLine() end
function Recipe.GetItemTypes.MeatCleaver() end
function Recipe.GetItemTypes.MixingUtensil() end
---@class Recipe_OnCanPerform
---@field CleanMuffin any
---@field GetBiscuit any
---@field HalloweenPumpkin any
---@field HockeyMaskSmashBottle any
---@field OpenFire any
---@field RipClothing any
---@field SliceCooked any
---@field SlicePizza any
---@field Uncooked any
Recipe.OnCanPerform = Recipe.OnCanPerform or {}
function Recipe.OnCanPerform.CleanMuffin() end
function Recipe.OnCanPerform.GetBiscuit() end
function Recipe.OnCanPerform.HalloweenPumpkin() end
function Recipe.OnCanPerform.HockeyMaskSmashBottle() end
function Recipe.OnCanPerform.OpenFire() end
function Recipe.OnCanPerform.RipClothing() end
function Recipe.OnCanPerform.SliceCooked() end
function Recipe.OnCanPerform.SlicePizza() end
function Recipe.OnCanPerform.Uncooked() end
---@class Recipe_OnCreate
---@field AddBaseIngredientToCookingVessel any
---@field AddToPack any
---@field BasicCarving any
---@field BasicCondition any
---@field BasicGrindMetal any
---@field BasicKnapping any
---@field BasicSawMetal any
---@field BeanBowl any
---@field Blacksmith1 any
---@field Blacksmith10 any
---@field Blacksmith10_NoProductCondition any
---@field Blacksmith1_NoProductCondition any
---@field Blacksmith20 any
---@field Blacksmith20_NoProductCondition any
---@field Blacksmith25 any
---@field Blacksmith25_NoProductCondition any
---@field BlacksmithGeneral any
---@field BreakOnSmith any
---@field CannedFood any
---@field CarvePumpkin any
---@field CarveSpear any
---@field ChangeSawblade any
---@field CleanTaintedFood any
---@field CloseUmbrella any
---@field CreateFishingRod any
---@field CreateLogStack any
---@field CreateSpear any
---@field CreateUnpack any
---@field CutAnimal any
---@field CutChicken any
---@field CutFillet any
---@field CutFish any
---@field Dismantle any
---@field Dismantle2 any
---@field DismantleBlade any
---@field DismantleFlashlight any
---@field DismantleMiscElectronics any
---@field DismantleRadio any
---@field DismantleRadioHAM any
---@field DismantleRadioSpecial any
---@field DismantleRadioTV any
---@field DismantleRadioTwoWay any
---@field DismantleSpear any
---@field DrawRandomCard any
---@field DynamicMovable any
---@field EmptyDrainable any
---@field ExtinguishHurricaneLantern any
---@field FireHardenSpear any
---@field FixFishingRod any
---@field GasmaskFilterInsert any
---@field GasmaskFilterRemoval any
---@field GatherGunpowder any
---@field GenericSharpen any
---@field GetBiscuit any
---@field GetCookies any
---@field GetMuffin any
---@field HarvestRoe any
---@field HollowBook any
---@field HotCuppa any
---@field InheritColorFromMaterial any
---@field InheritTextureVariation any
---@field KnappFlake any
---@field LightHurricaneLantern any
---@field Make2Bowls any
---@field Make4Bowls any
---@field MakeBlunt any
---@field MakeBowlOfSoup2 any
---@field MakeBowlOfSoup4 any
---@field MakeBowlOfStew4 any
---@field MakeCoffee any
---@field MakeCooked any
---@field MakeMilkFromPowder any
---@field MakeOatmeal any
---@field MakeOmelette any
---@field MakeSushi any
---@field MakeWireFromBarbedWire any
---@field MeatPatty any
---@field MinorCarving any
---@field MinorCondition any
---@field MinorKnapping any
---@field MinorMasonry any
---@field OpenBagFrozenFood any
---@field OpenBeer any
---@field OpenBoxOfJars any
---@field OpenCan any
---@field OpenCandyPackage any
---@field OpenCannedFood any
---@field OpenChampagne any
---@field OpenDentedCan any
---@field OpenDentedCanKnife any
---@field OpenEggCarton any
---@field OpenMysteryCan any
---@field OpenMysteryCanKnife any
---@field OpenRoeJar any
---@field OpenSackProduce any
---@field OpenUmbrella any
---@field OpenWaterCan any
---@field OpenWaterCanKnife any
---@field OxygenTankAttach any
---@field OxygenTankRemoval any
---@field PickAramidThread any
---@field PickThread any
---@field PlaceInBox any
---@field Propane_RefillInsert any
---@field Propane_RefillRemoval any
---@field PurifyWater any
---@field PutCakeBatterInBakingPan any
---@field PutEggsInCarton any
---@field RadioCraft any
---@field RefillBlowTorch any
---@field RefillHurricaneLantern any
---@field RefillLighter any
---@field RemoveGem any
---@field RepairBladeWithGrindstone any
---@field RipClothing any
---@field RoeJar any
---@field Roll3d6 any
---@field RollDice any
---@field RollOneDice any
---@field Rolld100 any
---@field ScrapJewellery any
---@field ScratchTicket any
---@field SetEcruColor any
---@field SewHideJacket any
---@field SharpenBlade any
---@field SharpenBladeGrindstone any
---@field SharpenBladePoor any
---@field SharpenBladeWithGrindstone any
---@field ShotgunSawnoff any
---@field Slice3 any
---@field Slice5 any
---@field SliceAnimalHead any
---@field SliceBread any
---@field SliceHam any
---@field SliceOnion any
---@field SlicePie any
---@field SlicePizza any
---@field SliceSalami any
---@field SliceWatermelon any
---@field SlightlyMoreDurable any
---@field SmeltIronOrSteel any
---@field SmeltIronOrSteelIngot any
---@field SmeltIronOrSteelLarge any
---@field SmeltIronOrSteelMedium any
---@field SmeltIronOrSteelMediumPlus any
---@field SmeltIronOrSteelSmall any
---@field SpikedBat any
---@field SplitFirewoodBundle any
---@field SplitLogStack any
---@field SplitLogStack2 any
---@field SplitLogStack3 any
---@field SplitLogStack4 any
---@field TorchBatteryInsert any
---@field TorchBatteryRemoval any
---@field UnpackBox any
---@field UntieHeadband any
---@field UpgradeSpear any
---@field WashClothing any
---@field WornGasmaskFilterInsert any
Recipe.OnCreate = Recipe.OnCreate or {}
function Recipe.OnCreate.AddBaseIngredientToCookingVessel() end
function Recipe.OnCreate.AddToPack() end
function Recipe.OnCreate.BasicCarving() end
function Recipe.OnCreate.BasicCondition() end
function Recipe.OnCreate.BasicGrindMetal() end
function Recipe.OnCreate.BasicKnapping() end
function Recipe.OnCreate.BasicSawMetal() end
function Recipe.OnCreate.BeanBowl() end
function Recipe.OnCreate.Blacksmith1() end
function Recipe.OnCreate.Blacksmith10() end
function Recipe.OnCreate.Blacksmith10_NoProductCondition() end
function Recipe.OnCreate.Blacksmith1_NoProductCondition() end
function Recipe.OnCreate.Blacksmith20() end
function Recipe.OnCreate.Blacksmith20_NoProductCondition() end
function Recipe.OnCreate.Blacksmith25() end
function Recipe.OnCreate.Blacksmith25_NoProductCondition() end
function Recipe.OnCreate.BlacksmithGeneral() end
function Recipe.OnCreate.BreakOnSmith() end
function Recipe.OnCreate.CannedFood() end
function Recipe.OnCreate.CarvePumpkin() end
function Recipe.OnCreate.CarveSpear() end
function Recipe.OnCreate.ChangeSawblade() end
function Recipe.OnCreate.CleanTaintedFood() end
function Recipe.OnCreate.CloseUmbrella() end
function Recipe.OnCreate.CreateFishingRod() end
function Recipe.OnCreate.CreateLogStack() end
function Recipe.OnCreate.CreateUnpack() end
function Recipe.OnCreate.CutAnimal() end
function Recipe.OnCreate.CutChicken() end
function Recipe.OnCreate.CutFillet() end
function Recipe.OnCreate.CutFish() end
function Recipe.OnCreate.Dismantle2() end
function Recipe.OnCreate.DismantleBlade() end
function Recipe.OnCreate.DismantleFlashlight() end
function Recipe.OnCreate.DismantleMiscElectronics() end
function Recipe.OnCreate.DismantleRadio() end
function Recipe.OnCreate.DismantleRadioSpecial() end
function Recipe.OnCreate.DismantleRadioTV() end
function Recipe.OnCreate.DismantleRadioTwoWay() end
function Recipe.OnCreate.DismantleSpear() end
function Recipe.OnCreate.DrawRandomCard() end
function Recipe.OnCreate.DynamicMovable() end
function Recipe.OnCreate.EmptyDrainable() end
function Recipe.OnCreate.ExtinguishHurricaneLantern() end
function Recipe.OnCreate.FireHardenSpear() end
function Recipe.OnCreate.FixFishingRod() end
function Recipe.OnCreate.GasmaskFilterInsert() end
function Recipe.OnCreate.GasmaskFilterRemoval() end
function Recipe.OnCreate.GatherGunpowder() end
function Recipe.OnCreate.GenericSharpen() end
function Recipe.OnCreate.GetBiscuit() end
function Recipe.OnCreate.GetCookies() end
function Recipe.OnCreate.GetMuffin() end
function Recipe.OnCreate.HarvestRoe() end
function Recipe.OnCreate.HollowBook() end
function Recipe.OnCreate.HotCuppa() end
function Recipe.OnCreate.InheritColorFromMaterial() end
function Recipe.OnCreate.InheritTextureVariation() end
function Recipe.OnCreate.KnappFlake() end
function Recipe.OnCreate.LightHurricaneLantern() end
function Recipe.OnCreate.Make2Bowls() end
function Recipe.OnCreate.Make4Bowls() end
function Recipe.OnCreate.MakeBlunt() end
function Recipe.OnCreate.MakeCoffee() end
function Recipe.OnCreate.MakeCooked() end
function Recipe.OnCreate.MakeMilkFromPowder() end
function Recipe.OnCreate.MakeOatmeal() end
function Recipe.OnCreate.MakeOmelette() end
function Recipe.OnCreate.MakeSushi() end
function Recipe.OnCreate.MakeWireFromBarbedWire() end
function Recipe.OnCreate.MeatPatty() end
function Recipe.OnCreate.MinorCarving() end
function Recipe.OnCreate.MinorCondition() end
function Recipe.OnCreate.MinorKnapping() end
function Recipe.OnCreate.MinorMasonry() end
function Recipe.OnCreate.OpenBagFrozenFood() end
function Recipe.OnCreate.OpenBeer() end
function Recipe.OnCreate.OpenCan() end
function Recipe.OnCreate.OpenCannedFood() end
function Recipe.OnCreate.OpenChampagne() end
function Recipe.OnCreate.OpenDentedCan() end
function Recipe.OnCreate.OpenDentedCanKnife() end
function Recipe.OnCreate.OpenEggCarton() end
function Recipe.OnCreate.OpenMysteryCan() end
function Recipe.OnCreate.OpenMysteryCanKnife() end
function Recipe.OnCreate.OpenRoeJar() end
function Recipe.OnCreate.OpenSackProduce() end
function Recipe.OnCreate.OpenWaterCan() end
function Recipe.OnCreate.OpenWaterCanKnife() end
function Recipe.OnCreate.OxygenTankAttach() end
function Recipe.OnCreate.OxygenTankRemoval() end
function Recipe.OnCreate.PickAramidThread() end
function Recipe.OnCreate.PickThread() end
function Recipe.OnCreate.PlaceInBox() end
function Recipe.OnCreate.Propane_RefillInsert() end
function Recipe.OnCreate.Propane_RefillRemoval() end
function Recipe.OnCreate.PurifyWater() end
function Recipe.OnCreate.PutEggsInCarton() end
function Recipe.OnCreate.RadioCraft() end
function Recipe.OnCreate.RefillBlowTorch() end
function Recipe.OnCreate.RefillHurricaneLantern() end
function Recipe.OnCreate.RefillLighter() end
function Recipe.OnCreate.RemoveGem() end
function Recipe.OnCreate.RepairBladeWithGrindstone() end
function Recipe.OnCreate.RipClothing() end
function Recipe.OnCreate.RoeJar() end
function Recipe.OnCreate.Roll3d6() end
function Recipe.OnCreate.RollDice() end
function Recipe.OnCreate.RollOneDice() end
function Recipe.OnCreate.Rolld100() end
function Recipe.OnCreate.ScrapJewellery() end
function Recipe.OnCreate.ScratchTicket() end
function Recipe.OnCreate.SetEcruColor() end
function Recipe.OnCreate.SewHideJacket() end
function Recipe.OnCreate.SharpenBlade() end
function Recipe.OnCreate.SharpenBladeGrindstone() end
function Recipe.OnCreate.SharpenBladePoor() end
function Recipe.OnCreate.SharpenBladeWithGrindstone() end
function Recipe.OnCreate.ShotgunSawnoff() end
function Recipe.OnCreate.Slice3() end
function Recipe.OnCreate.Slice5() end
function Recipe.OnCreate.SliceAnimalHead() end
function Recipe.OnCreate.SliceHam() end
function Recipe.OnCreate.SliceOnion() end
function Recipe.OnCreate.SlicePizza() end
function Recipe.OnCreate.SliceSalami() end
function Recipe.OnCreate.SliceWatermelon() end
function Recipe.OnCreate.SlightlyMoreDurable() end
function Recipe.OnCreate.SmeltIronOrSteel() end
function Recipe.OnCreate.SmeltIronOrSteelIngot() end
function Recipe.OnCreate.SmeltIronOrSteelLarge() end
function Recipe.OnCreate.SmeltIronOrSteelMedium() end
function Recipe.OnCreate.SmeltIronOrSteelMediumPlus() end
function Recipe.OnCreate.SmeltIronOrSteelSmall() end
function Recipe.OnCreate.SpikedBat() end
function Recipe.OnCreate.SplitFirewoodBundle() end
function Recipe.OnCreate.SplitLogStack() end
function Recipe.OnCreate.TorchBatteryInsert() end
function Recipe.OnCreate.TorchBatteryRemoval() end
function Recipe.OnCreate.UnpackBox() end
function Recipe.OnCreate.UntieHeadband() end
function Recipe.OnCreate.UpgradeSpear() end
function Recipe.OnCreate.WashClothing() end
function Recipe.OnCreate.WornGasmaskFilterInsert() end
---@class Recipe_OnGiveXP
---@field Blacksmith10 any
---@field Blacksmith15 any
---@field Blacksmith20 any
---@field Blacksmith25 any
---@field Cooking10 any
---@field Cooking3 any
---@field Default any
---@field DismantleElectronics any
---@field DismantleRadio any
---@field DynamicMovable any
---@field MetalWelding10 any
---@field MetalWelding15 any
---@field MetalWelding20 any
---@field MetalWelding25 any
---@field None any
---@field RadioCraft any
---@field SawLogs any
---@field WoodWork5 any
Recipe.OnGiveXP = Recipe.OnGiveXP or {}
function Recipe.OnGiveXP.Default() end
function Recipe.OnGiveXP.DismantleElectronics() end
function Recipe.OnGiveXP.DismantleRadio() end
function Recipe.OnGiveXP.DynamicMovable() end
function Recipe.OnGiveXP.RadioCraft() end
function Recipe.OnGiveXP.SawLogs() end
---@class Recipe_OnTest
---@field BottleNotOpened any
---@field BottleNotOpenedNotTainted any
---@field BreakGlass any
---@field CanAddToPack any
---@field CutFillet any
---@field CutFish any
---@field EmptyBag any
---@field EntityRepairFull any
---@field FullPetrolBottle any
---@field FullRoll any
---@field GasmaskFilterCraftedRemoval any
---@field GasmaskFilterInsert any
---@field GasmaskFilterNotFull any
---@field GasmaskFilterRemoval any
---@field GenericPacking any
---@field HotFluidContainer any
---@field IsFull any
---@field MakeMilkFromPowder any
---@field NormalGoodFullFood any
---@field NotTainted any
---@field NotTaintedWater any
---@field NotWornLowerBody any
---@field OnlyBrokenHandle any
---@field OnlyBrokenSaw any
---@field OxygenTankAttach any
---@field OxygenTankRemoval any
---@field Propane_RefillInsert any
---@field Propane_RefillRemoval any
---@field PurifyWater any
---@field RefillBlowTorch any
---@field RefillHurricaneLantern any
---@field RespiratorFilterNotFull any
---@field RespiratorFilterRechargedRemoval any
---@field RespiratorFilterRemoval any
---@field ScratchTicket any
---@field SliceBreadDough any
---@field SmeltIronOrSteel any
---@field SmeltIronOrSteelIngot any
---@field SmeltIronOrSteelLarge any
---@field SmeltIronOrSteelMedium any
---@field SmeltIronOrSteelMediumPlus any
---@field SmeltIronOrSteelSmall any
---@field TaintedFood any
---@field TorchBatteryInsert any
---@field TorchBatteryRemoval any
---@field WashClothing any
---@field WholeBreadSlices any
---@field WornGasmaskFilterInsert any
Recipe.OnTest = Recipe.OnTest or {}
function Recipe.OnTest.BottleNotOpened() end
function Recipe.OnTest.BottleNotOpenedNotTainted() end
function Recipe.OnTest.BreakGlass() end
function Recipe.OnTest.CanAddToPack() end
function Recipe.OnTest.CutFillet() end
function Recipe.OnTest.CutFish() end
function Recipe.OnTest.EmptyBag() end
function Recipe.OnTest.EntityRepairFull() end
function Recipe.OnTest.FullPetrolBottle() end
function Recipe.OnTest.FullRoll() end
function Recipe.OnTest.GasmaskFilterCraftedRemoval() end
function Recipe.OnTest.GasmaskFilterInsert() end
function Recipe.OnTest.GasmaskFilterNotFull() end
function Recipe.OnTest.GasmaskFilterRemoval() end
function Recipe.OnTest.GenericPacking() end
function Recipe.OnTest.HotFluidContainer() end
function Recipe.OnTest.IsFull() end
function Recipe.OnTest.MakeMilkFromPowder() end
function Recipe.OnTest.NormalGoodFullFood() end
function Recipe.OnTest.NotTainted() end
function Recipe.OnTest.NotTaintedWater() end
function Recipe.OnTest.NotWornLowerBody() end
function Recipe.OnTest.OnlyBrokenHandle() end
function Recipe.OnTest.OnlyBrokenSaw() end
function Recipe.OnTest.OxygenTankAttach() end
function Recipe.OnTest.OxygenTankRemoval() end
function Recipe.OnTest.Propane_RefillInsert() end
function Recipe.OnTest.Propane_RefillRemoval() end
function Recipe.OnTest.PurifyWater() end
function Recipe.OnTest.RefillHurricaneLantern() end
function Recipe.OnTest.RespiratorFilterNotFull() end
function Recipe.OnTest.RespiratorFilterRechargedRemoval() end
function Recipe.OnTest.RespiratorFilterRemoval() end
function Recipe.OnTest.ScratchTicket() end
function Recipe.OnTest.SliceBreadDough() end
function Recipe.OnTest.SmeltIronOrSteel() end
function Recipe.OnTest.SmeltIronOrSteelIngot() end
function Recipe.OnTest.SmeltIronOrSteelLarge() end
function Recipe.OnTest.SmeltIronOrSteelMedium() end
function Recipe.OnTest.SmeltIronOrSteelMediumPlus() end
function Recipe.OnTest.SmeltIronOrSteelSmall() end
function Recipe.OnTest.TaintedFood() end
function Recipe.OnTest.WashClothing() end
function Recipe.OnTest.WholeBreadSlices() end
function Recipe.OnTest.WornGasmaskFilterInsert() end
---@class Recipe_WeaponParts
---@field hasScrewdriver any
Recipe.WeaponParts = Recipe.WeaponParts or {}
function Recipe.WeaponParts.hasScrewdriver() end
