---@meta
---@class ShotgunStep
---@field Aiming any
---@field BackOverFence any
---@field BrothersDead any
---@field ClimbedFence any
---@field OnSquare any
---@field Outhouse any
---@field Shout any
---@field Sprinted any
---@field SurvivalGuideOpen any
---@field TheEnd any
---@field block any
---@field brotherWakeupTimer any
---@field finished any
---@field forceSpawnHorde any
---@field forcedShoutBinding any
---@field hassprintedTimer any
---@field isPlayedDead any
---@field isPlayedDeadJoypad any
---@field lockedX any
---@field lockedY any
---@field outhouseSQ any
---@field playerUpdate any
---@field sneaked any
---@field soundDone any
---@field soundTimer any
---@field spawnedHorde any
---@field squares any
---@field tickBeforeHordeSpawn any
---@field timeOfDeath any
---@field vaulted any
---@field block any
---@field brotherWakeupTimer any
---@field finished any
---@field forceSpawnHorde any
---@field forcedShoutBinding any
---@field hassprintedTimer any
---@field lockedX any
---@field lockedY any
---@field outhouseSQ any
---@field sneaked any
---@field soundDone any
---@field soundTimer any
---@field spawnedHorde any
---@field squares any
---@field tickBeforeHordeSpawn any
---@field timeOfDeath any
---@field vaulted any
ShotgunStep = ShotgunStep or {}

function ShotgunStep.BackOverFence() end
function ShotgunStep.BrothersDead() end
function ShotgunStep.ClimbedFence() end
function ShotgunStep.OnSquare() end
function ShotgunStep.Outhouse() end
function ShotgunStep.Sprinted() end
function ShotgunStep.SurvivalGuideOpen() end
function ShotgunStep.TheEnd() end
function ShotgunStep.playerUpdate() end
function ShotgunStep.playerUpdate(player) end
