---@meta
---@class SpecialLootSpawns
---@field ArmorSchematics any
---@field BSToolsSchematics any
---@field BookDetails any
---@field BookSubjects any
---@field BookSubjectsFictionGenres any
---@field BookSubjectsHardCover any
---@field BookSubjectsNonFiction any
---@field BookSubjectsPoor any
---@field BookSubjectsRich any
---@field BookSubjectsScary any
---@field BookTitles any
---@field BusinessCards any
---@field Catalogues any
---@field ComicBookDetails any
---@field ComicBooks any
---@field CookwareSchematic any
---@field CreateSchematic any
---@field DogTags any
---@field Doodle any
---@field DoodleKids any
---@field ExplosiveSchematics any
---@field FirstAidKit_New any
---@field FirstAidKit_NewPro any
---@field FoodRecipes any
---@field GenericMail any
---@field GetCoverFromList any
---@field JobTitles any
---@field LetterHandwritten any
---@field Locket any
---@field MagazineDetails any
---@field MagazineSubjects any
---@field Magazines any
---@field MeleeWeaponSchematics any
---@field OldPhotos any
---@field OnCreateAdventureNonFictionBook any
---@field OnCreateArmorSchematic any
---@field OnCreateArtBook any
---@field OnCreateArtMagazine any
---@field OnCreateBSToolsSchematic any
---@field OnCreateBaseballBook any
---@field OnCreateBibleBook any
---@field OnCreateBiographyBook any
---@field OnCreateBook any
---@field OnCreateBrochure any
---@field OnCreateBusinessBook any
---@field OnCreateBusinessCard any
---@field OnCreateBusinessCard_Nolans any
---@field OnCreateBusinessMagazine any
---@field OnCreateCanteen any
---@field OnCreateCanteenMilitary any
---@field OnCreateCarMagazine any
---@field OnCreateCard_Christmas any
---@field OnCreateCatalogue any
---@field OnCreateChildsBook any
---@field OnCreateChildsMagazine any
---@field OnCreateChildsPictureBook any
---@field OnCreateCinemaBook any
---@field OnCreateCinemaMagazine any
---@field OnCreateClassicBook any
---@field OnCreateClassicFictionBook any
---@field OnCreateClassicNonfictionBook any
---@field OnCreateColorFromDefinition any
---@field OnCreateComicBook any
---@field OnCreateComicBookRetail any
---@field OnCreateComputerBook any
---@field OnCreateConspiracyBook any
---@field OnCreateCookwareSchematic any
---@field OnCreateCrimeFictionBook any
---@field OnCreateCrimeMagazine any
---@field OnCreateDietBook any
---@field OnCreateDispatchNewNewspaper any
---@field OnCreateDogTag any
---@field OnCreateDogTag_Female any
---@field OnCreateDogTag_Male any
---@field OnCreateDogTag_Pet any
---@field OnCreateDoodle any
---@field OnCreateDoodleKids any
---@field OnCreateExplosivesSchematic any
---@field OnCreateFantasyBook any
---@field OnCreateFarmingBook any
---@field OnCreateFashionBook any
---@field OnCreateFashionMagazine any
---@field OnCreateFictionBook any
---@field OnCreateFirearmMagazine any
---@field OnCreateFlier any
---@field OnCreateFlier_Nolans any
---@field OnCreateGamingMagazine any
---@field OnCreateGasMask any
---@field OnCreateGeneralNonFictionBook any
---@field OnCreateGeneralReferenceBook any
---@field OnCreateGenericMail any
---@field OnCreateGolfBook any
---@field OnCreateGolfMagazine any
---@field OnCreateHairDyeBottle any
---@field OnCreateHassBook any
---@field OnCreateHealthMagazine any
---@field OnCreateHeraldNewNewspaper any
---@field OnCreateHistoryBook any
---@field OnCreateHobbyMagazine any
---@field OnCreateHorrorBook any
---@field OnCreateHorrorMagazine any
---@field OnCreateHottieZ any
---@field OnCreateHumorMagazine any
---@field OnCreateHunkZ any
---@field OnCreateIDcard any
---@field OnCreateIDcard_Female any
---@field OnCreateIDcard_Male any
---@field OnCreateKnewsNewNewspaper any
---@field OnCreateLegalBook any
---@field OnCreateLetterHandwritten any
---@field OnCreateLiteraryFictionBook any
---@field OnCreateLocket any
---@field OnCreateMagazine any
---@field OnCreateMagazine2 any
---@field OnCreateMagazine3 any
---@field OnCreateMedicalBook any
---@field OnCreateMeleeWeaponSchematic any
---@field OnCreateMilitaryBook any
---@field OnCreateMilitaryHistoryBook any
---@field OnCreateMilitaryMagazine any
---@field OnCreateMonogram any
---@field OnCreateMusicBook any
---@field OnCreateMusicMagazine any
---@field OnCreateNatureBook any
---@field OnCreateNewAgeBook any
---@field OnCreateNewNewspaper any
---@field OnCreateNote any
---@field OnCreateOccultBook any
---@field OnCreateOldNewspaper any
---@field OnCreateOutdoorsMagazine any
---@field OnCreatePaperwork any
---@field OnCreatePhilosophyBook any
---@field OnCreatePhoto any
---@field OnCreatePhotoBook any
---@field OnCreatePhoto_Racy any
---@field OnCreatePhoto_Secret any
---@field OnCreatePhoto_VeryOld any
---@field OnCreatePlayBook any
---@field OnCreatePoliceMagazine any
---@field OnCreatePolicingBook any
---@field OnCreatePoliticsBook any
---@field OnCreatePoorBook any
---@field OnCreatePopBottle any
---@field OnCreatePopCan any
---@field OnCreatePopularMagazine any
---@field OnCreatePostcard any
---@field OnCreateQuackeryBook any
---@field OnCreateQuigleyBook any
---@field OnCreateRPGmanual any
---@field OnCreateRandomColor any
---@field OnCreateRecentNewspaper any
---@field OnCreateRecipeClipping any
---@field OnCreateRegion any
---@field OnCreateRelationshipBook any
---@field OnCreateReligionBook any
---@field OnCreateRespirator any
---@field OnCreateRichBook any
---@field OnCreateRichMagazine any
---@field OnCreateRomanceBook any
---@field OnCreateSCBA any
---@field OnCreateSadNonFictionBook any
---@field OnCreateScarecrow any
---@field OnCreateScaryBook any
---@field OnCreateSchoolTextbookBook any
---@field OnCreateSciFiBook any
---@field OnCreateScienceBook any
---@field OnCreateScienceMagazine any
---@field OnCreateScratchTicketWinner any
---@field OnCreateSealedParcel any
---@field OnCreateSelfHelpBook any
---@field OnCreateSewingPattern any
---@field OnCreateSexyBook any
---@field OnCreateSkeletonDisplay any
---@field OnCreateSnowGlobe any
---@field OnCreateSodaCan any
---@field OnCreateSpecialBook any
---@field OnCreateSportsBook any
---@field OnCreateSportsMagazine any
---@field OnCreateStockCertificate any
---@field OnCreateSubjectBook any
---@field OnCreateSubjectMagazine any
---@field OnCreateSurvivalSchematic any
---@field OnCreateTVMagazine any
---@field OnCreateTechMagazine any
---@field OnCreateTeensBook any
---@field OnCreateTeensMagazine any
---@field OnCreateThrillerBook any
---@field OnCreateTimesNewNewspaper any
---@field OnCreateTravelBook any
---@field OnCreateTrueCrimeBook any
---@field OnCreateWaterBottle any
---@field OnCreateWesternBook any
---@field Postcards any
---@field RPGs any
---@field RacyPhotos any
---@field SecretPhotos any
---@field SewingPatterns any
---@field StockCertificate1 any
---@field StockCertificate2 any
---@field SurvivalSchematics any
---@field VeryOldPhotos any
---@field ArmorSchematics any
---@field BSToolsSchematics any
---@field BookDetails any
---@field BookSubjects any
---@field BookSubjectsFictionGenres any
---@field BookSubjectsHardCover any
---@field BookSubjectsNonFiction any
---@field BookSubjectsPoor any
---@field BookSubjectsRich any
---@field BookSubjectsScary any
---@field BookTitles any
---@field BusinessCards any
---@field Catalogues any
---@field ComicBookDetails any
---@field ComicBooks any
---@field CookwareSchematic any
---@field CreateSchematic any
---@field DogTags any
---@field Doodle any
---@field DoodleKids any
---@field ExplosiveSchematics any
---@field FirstAidKit_New any
---@field FirstAidKit_NewPro any
---@field FoodRecipes any
---@field GenericMail any
---@field GetCoverFromList any
---@field JobTitles any
---@field LetterHandwritten any
---@field Locket any
---@field MagazineDetails any
---@field MagazineSubjects any
---@field Magazines any
---@field MeleeWeaponSchematics any
---@field OldPhotos any
---@field OnCreateAdventureNonFictionBook any
---@field OnCreateArmorSchematic any
---@field OnCreateArtBook any
---@field OnCreateArtMagazine any
---@field OnCreateBSToolsSchematic any
---@field OnCreateBaseballBook any
---@field OnCreateBibleBook any
---@field OnCreateBiographyBook any
---@field OnCreateBook any
---@field OnCreateBrochure any
---@field OnCreateBusinessBook any
---@field OnCreateBusinessCard any
---@field OnCreateBusinessCard_Nolans any
---@field OnCreateBusinessMagazine any
---@field OnCreateCanteen any
---@field OnCreateCanteenMilitary any
---@field OnCreateCarMagazine any
---@field OnCreateCard_Christmas any
---@field OnCreateCatalogue any
---@field OnCreateChildsBook any
---@field OnCreateChildsMagazine any
---@field OnCreateChildsPictureBook any
---@field OnCreateCinemaBook any
---@field OnCreateCinemaMagazine any
---@field OnCreateClassicBook any
---@field OnCreateClassicFictionBook any
---@field OnCreateClassicNonfictionBook any
---@field OnCreateColorFromDefinition any
---@field OnCreateComicBook any
---@field OnCreateComicBookRetail any
---@field OnCreateComputerBook any
---@field OnCreateConspiracyBook any
---@field OnCreateCookwareSchematic any
---@field OnCreateCrimeFictionBook any
---@field OnCreateCrimeMagazine any
---@field OnCreateDietBook any
---@field OnCreateDispatchNewNewspaper any
---@field OnCreateDogTag any
---@field OnCreateDogTag_Female any
---@field OnCreateDogTag_Male any
---@field OnCreateDogTag_Pet any
---@field OnCreateDoodle any
---@field OnCreateDoodleKids any
---@field OnCreateExplosivesSchematic any
---@field OnCreateFantasyBook any
---@field OnCreateFarmingBook any
---@field OnCreateFashionBook any
---@field OnCreateFashionMagazine any
---@field OnCreateFictionBook any
---@field OnCreateFirearmMagazine any
---@field OnCreateFlier any
---@field OnCreateFlier_Nolans any
---@field OnCreateGamingMagazine any
---@field OnCreateGasMask any
---@field OnCreateGeneralNonFictionBook any
---@field OnCreateGeneralReferenceBook any
---@field OnCreateGenericMail any
---@field OnCreateGolfBook any
---@field OnCreateGolfMagazine any
---@field OnCreateHairDyeBottle any
---@field OnCreateHassBook any
---@field OnCreateHealthMagazine any
---@field OnCreateHeraldNewNewspaper any
---@field OnCreateHistoryBook any
---@field OnCreateHobbyMagazine any
---@field OnCreateHorrorBook any
---@field OnCreateHorrorMagazine any
---@field OnCreateHottieZ any
---@field OnCreateHumorMagazine any
---@field OnCreateHunkZ any
---@field OnCreateIDcard any
---@field OnCreateIDcard_Female any
---@field OnCreateIDcard_Male any
---@field OnCreateKnewsNewNewspaper any
---@field OnCreateLegalBook any
---@field OnCreateLetterHandwritten any
---@field OnCreateLiteraryFictionBook any
---@field OnCreateLocket any
---@field OnCreateMagazine any
---@field OnCreateMagazine2 any
---@field OnCreateMagazine3 any
---@field OnCreateMedicalBook any
---@field OnCreateMeleeWeaponSchematic any
---@field OnCreateMilitaryBook any
---@field OnCreateMilitaryHistoryBook any
---@field OnCreateMilitaryMagazine any
---@field OnCreateMonogram any
---@field OnCreateMusicBook any
---@field OnCreateMusicMagazine any
---@field OnCreateNatureBook any
---@field OnCreateNewAgeBook any
---@field OnCreateNewNewspaper any
---@field OnCreateNote any
---@field OnCreateOccultBook any
---@field OnCreateOldNewspaper any
---@field OnCreateOutdoorsMagazine any
---@field OnCreatePaperwork any
---@field OnCreatePhilosophyBook any
---@field OnCreatePhoto any
---@field OnCreatePhotoBook any
---@field OnCreatePhoto_Racy any
---@field OnCreatePhoto_Secret any
---@field OnCreatePhoto_VeryOld any
---@field OnCreatePlayBook any
---@field OnCreatePoliceMagazine any
---@field OnCreatePolicingBook any
---@field OnCreatePoliticsBook any
---@field OnCreatePoorBook any
---@field OnCreatePopBottle any
---@field OnCreatePopCan any
---@field OnCreatePopularMagazine any
---@field OnCreatePostcard any
---@field OnCreateQuackeryBook any
---@field OnCreateQuigleyBook any
---@field OnCreateRPGmanual any
---@field OnCreateRandomColor any
---@field OnCreateRecentNewspaper any
---@field OnCreateRecipeClipping any
---@field OnCreateRegion any
---@field OnCreateRelationshipBook any
---@field OnCreateReligionBook any
---@field OnCreateRespirator any
---@field OnCreateRichBook any
---@field OnCreateRichMagazine any
---@field OnCreateRomanceBook any
---@field OnCreateSCBA any
---@field OnCreateSadNonFictionBook any
---@field OnCreateScarecrow any
---@field OnCreateScaryBook any
---@field OnCreateSchoolTextbookBook any
---@field OnCreateSciFiBook any
---@field OnCreateScienceBook any
---@field OnCreateScienceMagazine any
---@field OnCreateScratchTicketWinner any
---@field OnCreateSealedParcel any
---@field OnCreateSelfHelpBook any
---@field OnCreateSewingPattern any
---@field OnCreateSexyBook any
---@field OnCreateSkeletonDisplay any
---@field OnCreateSnowGlobe any
---@field OnCreateSodaCan any
---@field OnCreateSpecialBook any
---@field OnCreateSportsBook any
---@field OnCreateSportsMagazine any
---@field OnCreateStockCertificate any
---@field OnCreateSubjectBook any
---@field OnCreateSubjectMagazine any
---@field OnCreateSurvivalSchematic any
---@field OnCreateTVMagazine any
---@field OnCreateTechMagazine any
---@field OnCreateTeensBook any
---@field OnCreateTeensMagazine any
---@field OnCreateThrillerBook any
---@field OnCreateTimesNewNewspaper any
---@field OnCreateTravelBook any
---@field OnCreateTrueCrimeBook any
---@field OnCreateWaterBottle any
---@field OnCreateWesternBook any
---@field Postcards any
---@field RPGs any
---@field RacyPhotos any
---@field SecretPhotos any
---@field SewingPatterns any
---@field StockCertificate1 any
---@field StockCertificate2 any
---@field SurvivalSchematics any
---@field VeryOldPhotos any
SpecialLootSpawns = SpecialLootSpawns or {}

function SpecialLootSpawns.CreateSchematic() end
function SpecialLootSpawns.CreateSchematic(item, list, multipleChance) end
function SpecialLootSpawns.FirstAidKit_New(item) end
function SpecialLootSpawns.FirstAidKit_NewPro(item) end
function SpecialLootSpawns.GetCoverFromList() end
function SpecialLootSpawns.GetCoverFromList(item, hardcover, oldBookList) end
function SpecialLootSpawns.OnCreateAdventureNonFictionBook(item) end
function SpecialLootSpawns.OnCreateArmorSchematic(item) end
function SpecialLootSpawns.OnCreateArtBook(item) end
function SpecialLootSpawns.OnCreateArtMagazine(item) end
function SpecialLootSpawns.OnCreateBSToolsSchematic(item) end
function SpecialLootSpawns.OnCreateBaseballBook(item) end
function SpecialLootSpawns.OnCreateBibleBook(item) end
function SpecialLootSpawns.OnCreateBiographyBook(item) end
function SpecialLootSpawns.OnCreateBook() end
function SpecialLootSpawns.OnCreateBook(item) end
function SpecialLootSpawns.OnCreateBrochure(item) end
function SpecialLootSpawns.OnCreateBusinessBook(item) end
function SpecialLootSpawns.OnCreateBusinessCard(item) end
function SpecialLootSpawns.OnCreateBusinessCard_Nolans(item) end
function SpecialLootSpawns.OnCreateBusinessMagazine(item) end
function SpecialLootSpawns.OnCreateCanteen(item) end
function SpecialLootSpawns.OnCreateCanteenMilitary(item) end
function SpecialLootSpawns.OnCreateCarMagazine(item) end
function SpecialLootSpawns.OnCreateCard_Christmas(item) end
function SpecialLootSpawns.OnCreateCatalogue(item) end
function SpecialLootSpawns.OnCreateChildsBook(item) end
function SpecialLootSpawns.OnCreateChildsMagazine(item) end
function SpecialLootSpawns.OnCreateChildsPictureBook(item) end
function SpecialLootSpawns.OnCreateCinemaBook(item) end
function SpecialLootSpawns.OnCreateCinemaMagazine(item) end
function SpecialLootSpawns.OnCreateClassicBook(item) end
function SpecialLootSpawns.OnCreateClassicFictionBook(item) end
function SpecialLootSpawns.OnCreateClassicNonfictionBook(item) end
function SpecialLootSpawns.OnCreateColorFromDefinition(item) end
function SpecialLootSpawns.OnCreateComicBook(item) end
function SpecialLootSpawns.OnCreateComicBookRetail(item) end
function SpecialLootSpawns.OnCreateComputerBook(item) end
function SpecialLootSpawns.OnCreateConspiracyBook(item) end
function SpecialLootSpawns.OnCreateCookwareSchematic(item) end
function SpecialLootSpawns.OnCreateCrimeFictionBook(item) end
function SpecialLootSpawns.OnCreateCrimeMagazine(item) end
function SpecialLootSpawns.OnCreateDietBook(item) end
function SpecialLootSpawns.OnCreateDispatchNewNewspaper(item) end
function SpecialLootSpawns.OnCreateDogTag(item) end
function SpecialLootSpawns.OnCreateDogTag_Female() end
function SpecialLootSpawns.OnCreateDogTag_Female(item) end
function SpecialLootSpawns.OnCreateDogTag_Male() end
function SpecialLootSpawns.OnCreateDogTag_Male(item) end
function SpecialLootSpawns.OnCreateDogTag_Pet(item) end
function SpecialLootSpawns.OnCreateDoodle(item) end
function SpecialLootSpawns.OnCreateDoodleKids(item) end
function SpecialLootSpawns.OnCreateExplosivesSchematic(item) end
function SpecialLootSpawns.OnCreateFantasyBook(item) end
function SpecialLootSpawns.OnCreateFarmingBook(item) end
function SpecialLootSpawns.OnCreateFashionBook(item) end
function SpecialLootSpawns.OnCreateFashionMagazine(item) end
function SpecialLootSpawns.OnCreateFictionBook(item) end
function SpecialLootSpawns.OnCreateFirearmMagazine(item) end
function SpecialLootSpawns.OnCreateFlier(item) end
function SpecialLootSpawns.OnCreateFlier_Nolans(item) end
function SpecialLootSpawns.OnCreateGamingMagazine(item) end
function SpecialLootSpawns.OnCreateGasMask(item) end
function SpecialLootSpawns.OnCreateGeneralNonFictionBook(item) end
function SpecialLootSpawns.OnCreateGeneralReferenceBook(item) end
function SpecialLootSpawns.OnCreateGenericMail(item) end
function SpecialLootSpawns.OnCreateGolfBook(item) end
function SpecialLootSpawns.OnCreateGolfMagazine(item) end
function SpecialLootSpawns.OnCreateHairDyeBottle(item) end
function SpecialLootSpawns.OnCreateHassBook(item) end
function SpecialLootSpawns.OnCreateHealthMagazine(item) end
function SpecialLootSpawns.OnCreateHeraldNewNewspaper(item) end
function SpecialLootSpawns.OnCreateHistoryBook(item) end
function SpecialLootSpawns.OnCreateHobbyMagazine(item) end
function SpecialLootSpawns.OnCreateHorrorBook(item) end
function SpecialLootSpawns.OnCreateHorrorMagazine(item) end
function SpecialLootSpawns.OnCreateHottieZ(item) end
function SpecialLootSpawns.OnCreateHumorMagazine(item) end
function SpecialLootSpawns.OnCreateHunkZ() end
function SpecialLootSpawns.OnCreateHunkZ(item) end
function SpecialLootSpawns.OnCreateIDcard(item) end
function SpecialLootSpawns.OnCreateIDcard_Female() end
function SpecialLootSpawns.OnCreateIDcard_Female(item) end
function SpecialLootSpawns.OnCreateIDcard_Male() end
function SpecialLootSpawns.OnCreateIDcard_Male(item) end
function SpecialLootSpawns.OnCreateKnewsNewNewspaper(item) end
function SpecialLootSpawns.OnCreateLegalBook(item) end
function SpecialLootSpawns.OnCreateLetterHandwritten(item) end
function SpecialLootSpawns.OnCreateLiteraryFictionBook(item) end
function SpecialLootSpawns.OnCreateLocket(item) end
function SpecialLootSpawns.OnCreateMagazine(item) end
function SpecialLootSpawns.OnCreateMagazine2() end
function SpecialLootSpawns.OnCreateMagazine2(item) end
function SpecialLootSpawns.OnCreateMagazine3() end
function SpecialLootSpawns.OnCreateMagazine3(item, subject, bookList) end
function SpecialLootSpawns.OnCreateMedicalBook(item) end
function SpecialLootSpawns.OnCreateMeleeWeaponSchematic(item) end
function SpecialLootSpawns.OnCreateMilitaryBook(item) end
function SpecialLootSpawns.OnCreateMilitaryHistoryBook(item) end
function SpecialLootSpawns.OnCreateMilitaryMagazine(item) end
function SpecialLootSpawns.OnCreateMonogram(item) end
function SpecialLootSpawns.OnCreateMusicBook(item) end
function SpecialLootSpawns.OnCreateMusicMagazine(item) end
function SpecialLootSpawns.OnCreateNatureBook(item) end
function SpecialLootSpawns.OnCreateNewAgeBook(item) end
function SpecialLootSpawns.OnCreateNewNewspaper(item) end
function SpecialLootSpawns.OnCreateNote(item) end
function SpecialLootSpawns.OnCreateOccultBook(item) end
function SpecialLootSpawns.OnCreateOldNewspaper(item) end
function SpecialLootSpawns.OnCreateOutdoorsMagazine(item) end
function SpecialLootSpawns.OnCreatePaperwork(item) end
function SpecialLootSpawns.OnCreatePhilosophyBook(item) end
function SpecialLootSpawns.OnCreatePhoto(item) end
function SpecialLootSpawns.OnCreatePhotoBook(item) end
function SpecialLootSpawns.OnCreatePhoto_Racy(item) end
function SpecialLootSpawns.OnCreatePhoto_Secret(item) end
function SpecialLootSpawns.OnCreatePhoto_VeryOld(item) end
function SpecialLootSpawns.OnCreatePlayBook(item) end
function SpecialLootSpawns.OnCreatePoliceMagazine(item) end
function SpecialLootSpawns.OnCreatePolicingBook(item) end
function SpecialLootSpawns.OnCreatePoliticsBook(item) end
function SpecialLootSpawns.OnCreatePoorBook(item) end
function SpecialLootSpawns.OnCreatePopBottle(item) end
function SpecialLootSpawns.OnCreatePopCan(item) end
function SpecialLootSpawns.OnCreatePopularMagazine(item) end
function SpecialLootSpawns.OnCreatePostcard(item) end
function SpecialLootSpawns.OnCreateQuackeryBook(item) end
function SpecialLootSpawns.OnCreateQuigleyBook(item) end
function SpecialLootSpawns.OnCreateRPGmanual(item) end
function SpecialLootSpawns.OnCreateRandomColor(item) end
function SpecialLootSpawns.OnCreateRecentNewspaper(item) end
function SpecialLootSpawns.OnCreateRecipeClipping(item) end
function SpecialLootSpawns.OnCreateRelationshipBook(item) end
function SpecialLootSpawns.OnCreateReligionBook(item) end
function SpecialLootSpawns.OnCreateRespirator(item) end
function SpecialLootSpawns.OnCreateRichBook(item) end
function SpecialLootSpawns.OnCreateRichMagazine(item) end
function SpecialLootSpawns.OnCreateRomanceBook(item) end
function SpecialLootSpawns.OnCreateSCBA(item) end
function SpecialLootSpawns.OnCreateSadNonFictionBook(item) end
function SpecialLootSpawns.OnCreateScarecrow(item) end
function SpecialLootSpawns.OnCreateScaryBook(item) end
function SpecialLootSpawns.OnCreateSchoolTextbookBook(item) end
function SpecialLootSpawns.OnCreateSciFiBook(item) end
function SpecialLootSpawns.OnCreateScienceBook(item) end
function SpecialLootSpawns.OnCreateScienceMagazine(item) end
function SpecialLootSpawns.OnCreateScratchTicketWinner(result) end
function SpecialLootSpawns.OnCreateSealedParcel(item) end
function SpecialLootSpawns.OnCreateSelfHelpBook(item) end
function SpecialLootSpawns.OnCreateSewingPattern(item) end
function SpecialLootSpawns.OnCreateSexyBook(item) end
function SpecialLootSpawns.OnCreateSkeletonDisplay(item) end
function SpecialLootSpawns.OnCreateSnowGlobe(item) end
function SpecialLootSpawns.OnCreateSodaCan(item) end
function SpecialLootSpawns.OnCreateSpecialBook() end
function SpecialLootSpawns.OnCreateSpecialBook(item, subject) end
function SpecialLootSpawns.OnCreateSportsBook(item) end
function SpecialLootSpawns.OnCreateSportsMagazine(item) end
function SpecialLootSpawns.OnCreateStockCertificate(item) end
function SpecialLootSpawns.OnCreateSubjectBook() end
function SpecialLootSpawns.OnCreateSubjectBook(item, subject) end
function SpecialLootSpawns.OnCreateSubjectMagazine() end
function SpecialLootSpawns.OnCreateSubjectMagazine(item, subject) end
function SpecialLootSpawns.OnCreateSurvivalSchematic(item) end
function SpecialLootSpawns.OnCreateTVMagazine(item) end
function SpecialLootSpawns.OnCreateTechMagazine(item) end
function SpecialLootSpawns.OnCreateTeensBook(item) end
function SpecialLootSpawns.OnCreateTeensMagazine(item) end
function SpecialLootSpawns.OnCreateThrillerBook(item) end
function SpecialLootSpawns.OnCreateTimesNewNewspaper(item) end
function SpecialLootSpawns.OnCreateTravelBook(item) end
function SpecialLootSpawns.OnCreateTrueCrimeBook(item) end
function SpecialLootSpawns.OnCreateWaterBottle(item) end
function SpecialLootSpawns.OnCreateWesternBook(item) end
---@class SpecialLootSpawns_BookSubjects
---@field Hardcover any
SpecialLootSpawns.BookSubjects = SpecialLootSpawns.BookSubjects or {}
---@class SpecialLootSpawns_BookTitles
---@field AdventureNonFiction any
---@field Art any
---@field Baseball any
---@field Bible any
---@field Biography any
---@field Business any
---@field Childs any
---@field ChildsPicture_Special any
---@field Cinema any
---@field Classic any
---@field ClassicFiction any
---@field ClassicNonfiction any
---@field Computer any
---@field Conspiracy any
---@field CrimeFiction any
---@field Diet any
---@field Fantasy any
---@field Farming any
---@field Fashion any
---@field GeneralFiction any
---@field GeneralReference any
---@field Golf any
---@field Hass any
---@field History any
---@field Horror any
---@field Legal any
---@field Medical any
---@field Military any
---@field MilitaryHistory any
---@field Music any
---@field Nature any
---@field NewAge any
---@field Occult any
---@field Philosophy any
---@field Photo_Special any
---@field Play any
---@field Policing any
---@field Politics any
---@field Quackery any
---@field Quigley any
---@field Relationship any
---@field Religion any
---@field Romance any
---@field SadNonFiction any
---@field SchoolTextbook any
---@field SciFi any
---@field Science any
---@field SelfHelp any
---@field Sexy any
---@field Sports any
---@field Teens any
---@field Thriller any
---@field Travel any
---@field TrueCrime any
---@field Western any
---@field AdventureNonFiction any
---@field Art any
---@field Baseball any
---@field Bible any
---@field Biography any
---@field Business any
---@field Childs any
---@field ChildsPicture_Special any
---@field Cinema any
---@field Classic any
---@field ClassicFiction any
---@field ClassicNonfiction any
---@field Computer any
---@field Conspiracy any
---@field CrimeFiction any
---@field Diet any
---@field Fantasy any
---@field Farming any
---@field Fashion any
---@field GeneralFiction any
---@field GeneralReference any
---@field Golf any
---@field Hass any
---@field History any
---@field Horror any
---@field Legal any
---@field Medical any
---@field Military any
---@field MilitaryHistory any
---@field Music any
---@field Nature any
---@field NewAge any
---@field Occult any
---@field Philosophy any
---@field Photo_Special any
---@field Policing any
---@field Politics any
---@field Quackery any
---@field Quigley any
---@field Relationship any
---@field Religion any
---@field Romance any
---@field SadNonFiction any
---@field SchoolTextbook any
---@field SciFi any
---@field Science any
---@field SelfHelp any
---@field Sexy any
---@field Sports any
---@field Teens any
---@field Thriller any
---@field Travel any
---@field TrueCrime any
---@field Western any
SpecialLootSpawns.BookTitles = SpecialLootSpawns.BookTitles or {}
---@class SpecialLootSpawns_MagazineSubjects
---@field Art any
---@field Business any
---@field Cars any
---@field Childs any
---@field Cinema any
---@field Crime any
---@field Fashion any
---@field Firearm any
---@field Gaming any
---@field Golf any
---@field Health any
---@field Hobby any
---@field Horror any
---@field Humor any
---@field Military any
---@field Music any
---@field Outdoors any
---@field Police any
---@field Popular any
---@field Rich any
---@field Science any
---@field Sports any
---@field Tech any
---@field Teens any
---@field Art any
---@field Business any
---@field Cars any
---@field Childs any
---@field Cinema any
---@field Crime any
---@field Fashion any
---@field Firearm any
---@field Gaming any
---@field Golf any
---@field Health any
---@field Hobby any
---@field Horror any
---@field Humor any
---@field Military any
---@field Music any
---@field Outdoors any
---@field Police any
---@field Popular any
---@field Rich any
---@field Science any
---@field Sports any
---@field Tech any
---@field Teens any
SpecialLootSpawns.MagazineSubjects = SpecialLootSpawns.MagazineSubjects or {}
---@class SpecialLootSpawns_OnCreateRegion
---@field Newspaper_New any
---@field Newspaper_Recent any
---@field Newspaper_New any
---@field Newspaper_Recent any
SpecialLootSpawns.OnCreateRegion = SpecialLootSpawns.OnCreateRegion or {}
function SpecialLootSpawns.OnCreateRegion.Newspaper_New(item, region) end
function SpecialLootSpawns.OnCreateRegion.Newspaper_Recent(item, region) end
