---@meta
---@class YouHaveOneDay
---@field Add any
---@field AddPlayer any
---@field EveryDays any
---@field EveryHours any
---@field Init any
---@field OnGameStart any
---@field OnInitWorld any
---@field OnPlayerUpdate any
---@field OnZombieUpdate any
---@field RemovePlayer any
---@field Render any
---@field gameMode any
---@field hordeDiner any
---@field hordeFlat any
---@field hordeGasStation any
---@field hordeOffice any
---@field hordePark any
---@field hordeSpawned any
---@field hordeTownArea any
---@field hordeWood any
---@field hordeWoodCamp any
---@field hordes any
---@field hoursBeforeSpawn any
---@field id any
---@field image any
---@field png any
---@field world any
---@field x any
---@field y any
---@field z any
---@field Add any
---@field AddPlayer any
---@field EveryDays any
---@field EveryHours any
---@field Init any
---@field OnGameStart any
---@field OnInitWorld any
---@field OnPlayerUpdate any
---@field OnZombieUpdate any
---@field Render any
---@field gameMode any
---@field hordeDiner any
---@field hordeFlat any
---@field hordeGasStation any
---@field hordeOffice any
---@field hordePark any
---@field hordeSpawned any
---@field hordeTownArea any
---@field hordeWood any
---@field hordeWoodCamp any
---@field hordes any
---@field id any
---@field image any
---@field world any
---@field x any
---@field y any
---@field z any
YouHaveOneDay = YouHaveOneDay or {}

function YouHaveOneDay.Add() end
function YouHaveOneDay.AddPlayer(playerNum, playerObj) end
function YouHaveOneDay.EveryDays() end
function YouHaveOneDay.EveryHours() end
function YouHaveOneDay.Init() end
function YouHaveOneDay.OnGameStart() end
function YouHaveOneDay.OnInitWorld() end
function YouHaveOneDay.OnPlayerUpdate(zombie) end
function YouHaveOneDay.OnZombieUpdate(zombie) end
function YouHaveOneDay.RemovePlayer() end
function YouHaveOneDay.RemovePlayer(playerObj) end
function YouHaveOneDay.Render() end
